version: '3.8'

services:
  local_frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - .:/frontend
    working_dir: /frontend
    ports:
      - "8081:8081"
    environment:
      - WATCHPACK_POLLING=true
    command: npm start

  local_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://local_db:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    depends_on:
      - local_db

  local_db:
    image: timescale/timescaledb:latest-pg16
    container_name: local_db
    restart: always
    environment:
      TZ: Asia/Seoul
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - local_db

volumes:
  database:
